name: Amazon Tests

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests (chrome, firefox, edge)'
        required: false
        default: 'chrome'
      headed:
        description: 'Run tests in headed mode (true/false)'
        required: false
        default: 'false'
      parallel:
        description: 'Run tests in parallel (true/false)'
        required: false
        default: 'true'
      retries:
        description: 'Number of retries for failed tests'
        required: false
        default: '2'
      tag:
        description: 'Cypress tag to filter tests (example: @smoke)'
        required: false
        default: ''
  schedule:
    - cron: '0 0 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run Cypress Tests (Parallel or Ordered)
        uses: cypress-io/github-action@v6
        with:
          load-balance: true
          record: true
          parallel: ${{ github.event.inputs.parallel == 'true' }}
          group: 'Amazon Tests'
          browser: ${{ github.event.inputs.browser }}
          headed: ${{ github.event.inputs.headed }}
          config: retriesRunMode=${{ github.event.inputs.retries }}
          spec: ${{ github.event.inputs.parallel == 'false' && 'cypress/e2e/TC_01_LoginTest.cy.js,cypress/e2e/TC_02_CheckOutTest.cy.js,cypress/e2e/TC_03_WishListSession.cy.js,cypress/e2e/TC_04_ProductSearchAndFilter.cy.js,cypress/e2e/TC_05_ReviewAndRating.cy.js,cypress/e2e/TC_06_MutlitabHandel.cy.js' || '' }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Screenshots on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Videos Always
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
